<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tips [
	<!ELEMENT tips (tip*)>
	<!ELEMENT tip (#PCDATA)>
	<!ATTLIST tip name CDATA #REQUIRED>
]>
<tips>
	<tip name="GRUDU_launch_1">When connecting to Grid'5000 you should provide your SSH passphrase. You will just have to type it once per application lifetime. It won't be save on disk be it will stay in memory.</tip>
	<tip name="GRUDU_launch_2">When connecting to Grid'5000 your preferred acces frontale is chosen for classical cases but you can also select another frontale.</tip>
	<tip name="GRUDU_configuration_1">In the configuration panel you can modify every parameters of the connection (your preferred acces frontale, your username, your ssh key file and your passphrase)</tip>
	<tip name="GRUDU_configuration_2">In the misc panel of the configuration panel you can configure your cluster policy: if they are enabled or not, the KaDeploy partitions and the Batch Scheduler to use.</tip>
	<tip name="GRUDU_display_1">The clusters are displayed in the tree with four different colors : Gray when they are not enabled, White when they are enabled and do not have job of the user, Yellow when they are enabled and have jobs of the user in the waiting mode, and Green when they are enabled and have jobs that are running.</tip>
	<tip name="GRUDU_display_2">The vizualisation has three levels: The Grid level where you can find some information on all the grid, the cluster level where you can find information on the occupation of the cluster and the reservation realized on it, and the job level with all the ifnormation about it.</tip>
	<tip name="GRUDU_display_3">You can realize some operations by right clicking on the elements of the tree : updating the views, deleting some jobs or opening a terminal on the selected resource.</tip>
	<tip name="GRUDU_display_grid_1">In the grid view, you have a graph of the grid occupation, a table summarizing the information of the graph and (optionnaly) a table of the reservation realized by the user.</tip>
	<tip name="GRUDU_display_grid_2">In the grid view you can display different graphs for the same data such as a histogramm for all clusters or a pie of the nodes states.</tip>
	<tip name="GRUDU_display_grid_3">When you have some reservation running you can save the corresponding nodes and jobs in a directory from the user reservation table.</tip>
	<tip name="GRUDU_display_grid_4">You can change the properties of the graph presented and also save it in several different formats.</tip>
	<tip name="GRUDU_display_3">When you have realized some reservations you can see this nodes in a different color in order to identify them from the other nodes used by jobs.</tip>
	<tip name="GRUDU_display_cluster_1">When you select a cluster you have the information about the node states, and you also have the possibility to display a gantt chart of the jobs present on the cluster.</tip>
	<tip name="GRUDU_display_cluster_2">When you select a cluster three elements are displayed : a graph repsenting the nodes states, a table summarizing these information and a table of the jobs running and waiting on the cluster.</tip>
	<tip name="GRUDU_display_cluster_3">You can change the properties of the graph presented and also save it in several different formats.</tip>
	<tip name="GRUDU_display_job_1">When selecting a job in the tree you can see a lot of information such as the nodes used by this job or the walltime of your reservation, etc ...</tip>
	<tip name="GRUDU_reservation_main_1">When you click on the reservation button, the main panel displays a map of Grid'5000 where the sites you enabled are presented.</tip>
	<tip name="GRUDU_reservation_main_2">When you click on a site you can define the number of nodes you want to reserve. These information will be displayed in a tootip is the mouse is over the site.</tip>
	<tip name="GRUDU_reservation_main_3">You can define the walltime, the date of the reservation and the queue in the main panel of the reservation frame.</tip>
	<tip name="GRUDU_reservation_main_4">You can select the OAR grid sub behaviour for the reservation you are configuring.</tip>
	<tip name="GRUDU_reservation_main_5">You can define a script to launch when the reservation gets running in the main panel of the reservation frame.</tip>
	<tip name="GRUDU_reservation_properties_1">When realizing a reservation you can define OAR properties for each clusters of Grid'5000 that you will use.</tip>
	<tip name="GRUDU_reservation_status_1">When realizing a reservation, a status is displayed when all the oarsub commands have been executed on the OAR frontales.</tip>
	<tip name="GRUDU_terminal_1">When clicking on the terminal button you can open a terminal on the preferred access frontale.</tip>
	<tip name="GRUDU_terminal_2">You can open a terminal on each cluster frontale by right clicking on the cluster nodes of the tree and selecting the "open a shell" item.</tip>
	<tip name="GRUDU_terminal_3">You can open a terminal on the main node of a job by right clicking on the job node of the tree and selecting the "open a shell" item.</tip>
	<tip name="GRUDU_summary_1">You can display a summary of the Grid'5000 and User resources from which you can save these resources to a directory fo r a further use.</tip>
	<tip name="GRUDU_kadeploy_1">You can deploy KaDeploy images from GRUDU with a nice interface where you can select some nodes and the images to deploy on them.</tip>
	<tip name="GRUDU_kadeploy_2">When clicking the deploy button in the deploy frame, a status frame will display the evolution of your deployments where you will be able to know how the deployments go.</tip>
	<tip name="GRUDU_javahelp">When selecting the Help of GRUDU you can display the User manual and get some information about how to use GRUDU.</tip>					
</tips>